// Generated by XTract — Solidity to MultiversX Rust transpiler
// Source: DexTokenSwap.sol
//
// Transpiler version: post A1 + A2
//   A1 (variable-declaration-let-mut) — `uint256 x = …` → `let mut x: BigUint<Self::Api> = …` ✓
//   A2 (dynamic-storage-detection)    — reserves/balances detected without whitelist ✓
//
// Remaining manual corrections (pending further transpiler work):
//   · Mapping reads in expression context: self.reserves(&t) → self.reserves(&t).get()
//   · Storage write statements (reserves[t] = …) not yet emitted
//   · nonReentrant modifier: locked = true / locked = false wrappers not yet emitted

#![no_std]

use multiversx_sc::imports::*;

#[multiversx_sc::contract]
pub trait DexTokenSwap {
    #[storage_mapper("owner")]
    fn owner(&self) -> SingleValueMapper<ManagedAddress<Self::Api>>;

    #[storage_mapper("locked")]
    fn locked(&self) -> SingleValueMapper<bool>;

    #[storage_mapper("reserves")]
    fn reserves(&self, key: &ManagedAddress<Self::Api>) -> SingleValueMapper<BigUint<Self::Api>>;

    #[storage_mapper("balances")]
    fn balances(&self, key1: &ManagedAddress<Self::Api>, key2: &ManagedAddress<Self::Api>) -> SingleValueMapper<BigUint<Self::Api>>;

    #[event("Deposit")]
    fn deposit_event(&self, #[indexed] token: &ManagedAddress<Self::Api>, #[indexed] provider: &ManagedAddress<Self::Api>, amount: &BigUint<Self::Api>);

    #[event("Swap")]
    fn swap_event(&self, #[indexed] tokenIn: &ManagedAddress<Self::Api>, #[indexed] tokenOut: &ManagedAddress<Self::Api>, #[indexed] trader: &ManagedAddress<Self::Api>, #[indexed] amountIn: &BigUint<Self::Api>, amountOut: &BigUint<Self::Api>);

    #[event("Withdraw")]
    fn withdraw_event(&self, #[indexed] token: &ManagedAddress<Self::Api>, #[indexed] provider: &ManagedAddress<Self::Api>, amount: &BigUint<Self::Api>);

    #[init]
    fn init(&self) {
        self.owner().set(&(self.blockchain().get_caller()));
        self.locked().set(&false);
    }

    // ── deposit ───────────────────────────────────────────────────────────────
    #[endpoint]
    fn deposit(&self, token: ManagedAddress<Self::Api>, amount: BigUint<Self::Api>) {
        require!(!self.locked().get(), "Reentrant call");
        self.locked().set(&true);
        require!(amount > BigUint::from(0u32), "Amount must be positive");
        let caller = self.blockchain().get_caller();
        let new_reserve = self.reserves(&token).get() + &amount;
        self.reserves(&token).set(&new_reserve);
        let new_balance = self.balances(&token, &caller).get() + &amount;
        self.balances(&token, &caller).set(&new_balance);
        self.deposit_event(&token, &caller, &amount);
        self.locked().set(&false);
    }

    // ── withdraw ──────────────────────────────────────────────────────────────
    #[endpoint]
    fn withdraw(&self, token: ManagedAddress<Self::Api>, amount: BigUint<Self::Api>) {
        require!(!self.locked().get(), "Reentrant call");
        self.locked().set(&true);
        require!(amount > BigUint::from(0u32), "Amount must be positive");
        let caller = self.blockchain().get_caller();
        require!(self.balances(&token, &caller).get() >= amount, "Insufficient balance");
        require!(self.reserves(&token).get() >= amount, "Insufficient reserve");
        let new_balance = self.balances(&token, &caller).get() - &amount;
        self.balances(&token, &caller).set(&new_balance);
        let new_reserve = self.reserves(&token).get() - &amount;
        self.reserves(&token).set(&new_reserve);
        self.withdraw_event(&token, &caller, &amount);
        self.locked().set(&false);
    }

    // ── swap ──────────────────────────────────────────────────────────────────
    // Constant-product AMM: amountOut = amountIn * reserveOut / (reserveIn + amountIn)
    #[endpoint]
    fn swap(&self, tokenIn: ManagedAddress<Self::Api>, amountIn: BigUint<Self::Api>, tokenOut: ManagedAddress<Self::Api>) {
        require!(!self.locked().get(), "Reentrant call");
        self.locked().set(&true);
        require!(amountIn > BigUint::from(0u32), "Invalid input amount");
        require!(self.reserves(&tokenIn).get() > BigUint::from(0u32), "No liquidity for tokenIn");
        require!(self.reserves(&tokenOut).get() > BigUint::from(0u32), "No liquidity for tokenOut");
        let reserve_in = self.reserves(&tokenIn).get();
        let reserve_out = self.reserves(&tokenOut).get();
        let mut amount_out: BigUint<Self::Api> = (&amountIn * &reserve_out) / (&reserve_in + &amountIn);
        require!(amount_out > BigUint::from(0u32), "Insufficient output amount");
        self.reserves(&tokenIn).set(&(reserve_in + &amountIn));
        self.reserves(&tokenOut).set(&(reserve_out - &amount_out));
        let caller = self.blockchain().get_caller();
        self.swap_event(&tokenIn, &tokenOut, &caller, &amountIn, &amount_out);
        self.locked().set(&false);
    }

    // ── views ─────────────────────────────────────────────────────────────────

    /// Spot price scaled by 1e18: reserveOut * 1e18 / reserveIn
    #[view(getPrice)]
    fn get_price(&self, tokenIn: ManagedAddress<Self::Api>, tokenOut: ManagedAddress<Self::Api>) -> BigUint<Self::Api> {
        require!(self.reserves(&tokenIn).get() > BigUint::from(0u32), "No liquidity for tokenIn");
        require!(self.reserves(&tokenOut).get() > BigUint::from(0u32), "No liquidity for tokenOut");
        return (self.reserves(&tokenOut).get() * BigUint::from(1_000_000_000_000_000_000u64)) / self.reserves(&tokenIn).get();
    }

    /// Raw reserve balance for a token
    #[view(getReserve)]
    fn get_reserve(&self, token: ManagedAddress<Self::Api>) -> BigUint<Self::Api> {
        return self.reserves(&token).get();
    }

}
