// Generated by XTract — Solidity to MultiversX Rust transpiler
// Source: NftStaking.sol
//
// Patterns demonstrated:
//   - Single-key mapping with struct value (A5 load-mutate-store)
//   - block.timestamp → self.blockchain().get_block_timestamp()
//   - payable stake endpoint (maps to #[payable("*")] with EsdtTokenPayment on MultiversX)
//   - onlyOwner modifier
//   - Events: Staked, Unstaked, RewardsClaimed
//
// MultiversX production notes:
//   stake():        replace #[payable("EGLD")] with #[payable("*")] and read the
//                   NFT via self.call_value().single_esdt(); the tokenId becomes the ESDT nonce.
//   unstake():      return NFT via self.send().direct_esdt(&caller, &token_id, nonce, &1u32.into())
//   claimRewards(): mint reward ESDT via self.send().esdt_local_mint(...) then direct_esdt(...)

#![no_std]

use multiversx_sc::imports::*;

#[derive(TypeAbi, TopEncode, TopDecode, NestedEncode, NestedDecode, ManagedVecItem)]
pub struct StakeInfo<M: ManagedTypeApi> {
    pub owner: ManagedAddress<M>,
    pub stakedAt: BigUint<M>,
    pub active: bool
}

#[multiversx_sc::contract]
pub trait NftStaking {
    #[storage_mapper("owner")]
    fn owner(&self) -> SingleValueMapper<ManagedAddress<Self::Api>>;

    #[storage_mapper("rewardRate")]
    fn reward_rate(&self) -> SingleValueMapper<BigUint<Self::Api>>;

    #[storage_mapper("lockPeriod")]
    fn lock_period(&self) -> SingleValueMapper<BigUint<Self::Api>>;

    #[storage_mapper("totalStaked")]
    fn total_staked(&self) -> SingleValueMapper<BigUint<Self::Api>>;

    #[storage_mapper("stakes")]
    fn stakes(&self, key: &BigUint<Self::Api>) -> SingleValueMapper<StakeInfo>;

    #[event("Staked")]
    fn staked_event(&self, #[indexed] user: &ManagedAddress<Self::Api>, #[indexed] tokenId: &BigUint<Self::Api>, timestamp: &BigUint<Self::Api>);

    #[event("Unstaked")]
    fn unstaked_event(&self, #[indexed] user: &ManagedAddress<Self::Api>, #[indexed] tokenId: &BigUint<Self::Api>, timestamp: &BigUint<Self::Api>);

    #[event("RewardsClaimed")]
    fn rewards_claimed_event(&self, #[indexed] user: &ManagedAddress<Self::Api>, #[indexed] tokenId: &BigUint<Self::Api>, amount: &BigUint<Self::Api>);

    #[init]
    fn init(&self) {
        self.owner().set(&(self.blockchain().get_caller()));
        self.reward_rate().set(&(BigUint::from(100u32)));
        self.lock_period().set(&(BigUint::from(86400u32)));
        self.total_staked().set(&(BigUint::from(0u32)));
    }

    #[payable("EGLD")]
    #[endpoint]
    fn stake(&self, tokenId: BigUint<Self::Api>) {
        require!(tokenId > BigUint::from(0u32), "Invalid token ID");
        require!(!self.stakes(&tokenId).active, "Already staked");
        let mut s = self.stakes(&tokenId).get();
        s.owner = self.blockchain().get_caller();
        self.stakes(&tokenId).set(&s);
        let mut s = self.stakes(&tokenId).get();
        s.staked_at = self.blockchain().get_block_timestamp();
        self.stakes(&tokenId).set(&s);
        let mut s = self.stakes(&tokenId).get();
        s.active = true;
        self.stakes(&tokenId).set(&s);
        self.total_staked().set(&(self.total_staked().get() + BigUint::from(1u32)));
        self.staked_event(&self.blockchain().get_caller(), &tokenId.clone(), &self.blockchain().get_block_timestamp());
    }

    #[endpoint]
    fn unstake(&self, tokenId: BigUint<Self::Api>) {
        require!(self.stakes(&tokenId).active, "Not staked");
        require!(self.stakes(&tokenId).owner == self.blockchain().get_caller(), "Not your NFT");
        let mut s = self.stakes(&tokenId).get();
        s.active = false;
        self.stakes(&tokenId).set(&s);
        self.total_staked().set(&(self.total_staked().get() - BigUint::from(1u32)));
        self.unstaked_event(&self.blockchain().get_caller(), &tokenId.clone(), &self.blockchain().get_block_timestamp());
    }

    #[endpoint]
    fn claim_rewards(&self, tokenId: BigUint<Self::Api>) {
        require!(self.stakes(&tokenId).active, "Not staked");
        require!(self.stakes(&tokenId).owner == self.blockchain().get_caller(), "Not your NFT");
        let mut elapsed: BigUint<Self::Api> = self.blockchain().get_block_timestamp() - self.stakes(&tokenId).stakedAt;
        let mut rewards: BigUint<Self::Api> = self.reward_rate().get() * elapsed / BigUint::from(86400u32);
        require!(rewards > BigUint::from(0u32), "No rewards yet");
        let mut s = self.stakes(&tokenId).get();
        s.staked_at = self.blockchain().get_block_timestamp();
        self.stakes(&tokenId).set(&s);
        self.rewards_claimed_event(&self.blockchain().get_caller(), &tokenId.clone(), &rewards);
    }

    #[view(getStakeInfo)]
    fn get_stake_info(&self, tokenId: BigUint<Self::Api>) -> bool {
        return (self.stakes(&tokenId).active, self.stakes(&tokenId).stakedAt);
    }

    #[view(isStaked)]
    fn is_staked(&self, tokenId: BigUint<Self::Api>) -> bool {
        return self.stakes(&tokenId).active;
    }

    #[endpoint]
    fn set_reward_rate(&self, newRate: BigUint<Self::Api>) {
        require!(self.blockchain().get_caller() == owner, "Not owner");
        require!(newRate > BigUint::from(0u32), "Rate must be positive");
        self.reward_rate().set(&newRate);
    }

    #[endpoint]
    fn set_lock_period(&self, newPeriod: BigUint<Self::Api>) {
        require!(self.blockchain().get_caller() == owner, "Not owner");
        require!(newPeriod > BigUint::from(0u32), "Period must be positive");
        self.lock_period().set(&newPeriod);
    }

}
