// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    nftmarketplace
    (
        init => init
        create_nft => create_nft
        list_nft_for_sale => list_nft_for_sale
        buy_nft => buy_nft
        getCurrentOwner => get_current_owner
        getCurrentPrice => get_current_price
        getCurrentForSale => get_current_for_sale
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
