// Generated by XTract — Solidity to MultiversX Rust transpiler
// Source: Subscription.sol

#![no_std]

use multiversx_sc::imports::*;

// ── Structs ────────────────────────────────────────────────────────────────────
//
// Solidity structs with uint256/bool fields map to BigUint/bool in Rust.
// plan.duration and expiry timestamps use u64 (fits block.timestamp range).

#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, TypeAbi, Clone)]
pub struct Plan<M: ManagedTypeApi> {
    pub price: BigUint<M>,
    pub duration: u64,
    pub active: bool,
}

#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, TypeAbi, Clone)]
pub struct SubscriptionRecord {
    pub expires_at: u64,
    pub plan_id: u64,
    pub cancelled: bool,
}

// ── Contract ───────────────────────────────────────────────────────────────────

#[multiversx_sc::contract]
pub trait Subscription {

    // ── Storage ───────────────────────────────────────────────────────────────

    #[storage_mapper("owner")]
    fn owner(&self) -> SingleValueMapper<ManagedAddress<Self::Api>>;

    /// mapping(address => Plan[])
    /// VecMapper provides indexed, ordered storage (1-indexed).
    #[storage_mapper("servicePlans")]
    fn service_plans(&self, service: &ManagedAddress<Self::Api>) -> VecMapper<Plan<Self::Api>>;

    /// mapping(address => mapping(address => SubscriptionRecord))
    #[storage_mapper("subscriptions")]
    fn subscriptions(&self, user: &ManagedAddress<Self::Api>, service: &ManagedAddress<Self::Api>) -> SingleValueMapper<SubscriptionRecord>;

    /// mapping(address => uint256)
    #[storage_mapper("serviceBalance")]
    fn service_balance(&self, service: &ManagedAddress<Self::Api>) -> SingleValueMapper<BigUint<Self::Api>>;

    /// mapping(address => address)
    #[storage_mapper("serviceOwner")]
    fn service_owner(&self, service: &ManagedAddress<Self::Api>) -> SingleValueMapper<ManagedAddress<Self::Api>>;

    // ── Events ────────────────────────────────────────────────────────────────

    #[event("Subscribed")]
    fn subscribed_event(
        &self,
        #[indexed] user: &ManagedAddress<Self::Api>,
        #[indexed] service: &ManagedAddress<Self::Api>,
        #[indexed] plan_id: u64,
        expires_at: u64,
    );

    #[event("Renewed")]
    fn renewed_event(
        &self,
        #[indexed] user: &ManagedAddress<Self::Api>,
        #[indexed] service: &ManagedAddress<Self::Api>,
        new_expires_at: u64,
    );

    #[event("Cancelled")]
    fn cancelled_event(
        &self,
        #[indexed] user: &ManagedAddress<Self::Api>,
        #[indexed] service: &ManagedAddress<Self::Api>,
    );

    #[event("Withdrawn")]
    fn withdrawn_event(
        &self,
        #[indexed] service: &ManagedAddress<Self::Api>,
        #[indexed] service_owner: &ManagedAddress<Self::Api>,
        amount: &BigUint<Self::Api>,
    );

    // ── Init ──────────────────────────────────────────────────────────────────

    #[init]
    fn init(&self) {
        self.owner().set(&self.blockchain().get_caller());
    }

    // ── Service management ────────────────────────────────────────────────────

    /// registerService(address service)
    /// Caller becomes the service owner; service must not already be registered.
    #[endpoint(registerService)]
    fn register_service(&self, service: ManagedAddress<Self::Api>) {
        require!(self.service_owner(&service).is_empty(), "Service already registered");
        self.service_owner(&service).set(&self.blockchain().get_caller());
    }

    /// addPlan(address service, uint256 price, uint256 duration)
    /// onlyServiceOwner modifier inlined.
    #[endpoint(addPlan)]
    fn add_plan(&self, service: ManagedAddress<Self::Api>, price: BigUint<Self::Api>, duration: u64) {
        require!(
            self.blockchain().get_caller() == self.service_owner(&service).get(),
            "Not service owner"
        );
        require!(price > BigUint::zero(), "Price must be positive");
        require!(duration > 0u64, "Duration must be positive");
        let plan = Plan { price, duration, active: true };
        self.service_plans(&service).push(&plan);
    }

    /// deactivatePlan(address service, uint256 planId)
    /// onlyServiceOwner modifier inlined.
    #[endpoint(deactivatePlan)]
    fn deactivate_plan(&self, service: ManagedAddress<Self::Api>, plan_id: u64) {
        require!(
            self.blockchain().get_caller() == self.service_owner(&service).get(),
            "Not service owner"
        );
        let count = self.service_plans(&service).len() as u64;
        require!(plan_id < count, "Invalid plan");
        // VecMapper is 1-indexed
        let mut plan = self.service_plans(&service).get((plan_id + 1) as usize);
        plan.active = false;
        let _ = self.service_plans(&service).set((plan_id + 1) as usize, &plan);
    }

    // ── Subscription lifecycle ─────────────────────────────────────────────────

    /// subscribe(address service, uint256 planId) payable
    #[payable("EGLD")]
    #[endpoint]
    fn subscribe(&self, service: ManagedAddress<Self::Api>, plan_id: u64) {
        let plan_count = self.service_plans(&service).len() as u64;
        require!(plan_id < plan_count, "Invalid plan");
        let plan = self.service_plans(&service).get((plan_id + 1) as usize);
        require!(plan.active, "Plan not active");
        let payment = self.call_value().egld_value().clone_value();
        require!(payment >= plan.price, "Insufficient payment");
        let now = self.blockchain().get_block_timestamp();
        let expires_at = now + plan.duration;
        let caller = self.blockchain().get_caller();
        let sub = SubscriptionRecord { expires_at, plan_id, cancelled: false };
        self.subscriptions(&caller, &service).set(&sub);
        let new_balance = self.service_balance(&service).get() + &payment;
        self.service_balance(&service).set(&new_balance);
        self.subscribed_event(&caller, &service, plan_id, expires_at);
    }

    /// renew(address service) payable
    /// Extends from current expiresAt if not yet expired, otherwise from now.
    #[payable("EGLD")]
    #[endpoint]
    fn renew(&self, service: ManagedAddress<Self::Api>) {
        let caller = self.blockchain().get_caller();
        let mut sub = self.subscriptions(&caller, &service).get();
        require!(!sub.cancelled, "Subscription cancelled");
        let plan = self.service_plans(&service).get((sub.plan_id + 1) as usize);
        require!(plan.active, "Plan not active");
        let payment = self.call_value().egld_value().clone_value();
        require!(payment >= plan.price, "Insufficient payment");
        let now = self.blockchain().get_block_timestamp();
        let base = if sub.expires_at > now { sub.expires_at } else { now };
        sub.expires_at = base + plan.duration;
        self.subscriptions(&caller, &service).set(&sub);
        let new_balance = self.service_balance(&service).get() + &payment;
        self.service_balance(&service).set(&new_balance);
        self.renewed_event(&caller, &service, sub.expires_at);
    }

    /// cancel(address service) — no refund
    #[endpoint]
    fn cancel(&self, service: ManagedAddress<Self::Api>) {
        let caller = self.blockchain().get_caller();
        let mut sub = self.subscriptions(&caller, &service).get();
        require!(!sub.cancelled, "Already cancelled");
        sub.cancelled = true;
        self.subscriptions(&caller, &service).set(&sub);
        self.cancelled_event(&caller, &service);
    }

    // ── Views ──────────────────────────────────────────────────────────────────

    /// isActive(address user, address service) view returns (bool)
    #[view(isActive)]
    fn is_active(&self, user: ManagedAddress<Self::Api>, service: ManagedAddress<Self::Api>) -> bool {
        if self.subscriptions(&user, &service).is_empty() {
            return false;
        }
        let sub = self.subscriptions(&user, &service).get();
        let now = self.blockchain().get_block_timestamp();
        return !sub.cancelled && sub.expires_at > now;
    }

    /// planCount(address service) view returns (uint256)
    #[view(planCount)]
    fn plan_count(&self, service: ManagedAddress<Self::Api>) -> u64 {
        return self.service_plans(&service).len() as u64;
    }

    // ── Withdrawal ─────────────────────────────────────────────────────────────

    /// withdraw(address service) — onlyServiceOwner inlined
    #[endpoint]
    fn withdraw(&self, service: ManagedAddress<Self::Api>) {
        let caller = self.blockchain().get_caller();
        require!(caller == self.service_owner(&service).get(), "Not service owner");
        let amount = self.service_balance(&service).get();
        require!(amount > BigUint::zero(), "Nothing to withdraw");
        self.service_balance(&service).set(&BigUint::zero());
        self.withdrawn_event(&service, &caller, &amount);
    }
}
