// Generated by XTract — Solidity to MultiversX Rust transpiler
// Source: DaoGovernance.sol
//
// Patterns demonstrated:
//   - Proposal struct with six fields stored in single-key mapping (A5 load-mutate-store)
//   - Nested mapping hasVoted → two-key SingleValueMapper (A2 dynamic detection)
//   - onlyAfterDeadline modifier with proposals[id].deadline access
//   - block.timestamp comparisons for deadline enforcement
//   - Events: ProposalCreated, VoteCast, ProposalExecuted
//
// MultiversX production notes:
//   vote():    hasVoted[proposalId][msg.sender] = true maps to
//              self.has_voted(&proposal_id, &caller).set(true)  — add manually post-transpile.
//   execute(): replace bytes calldata execution with a typed MultiversX contract call:
//              self.send().contract_call(target, endpoint).execute_on_dest_context()
//   Note:      Control-flow ordering — the transpiler extracts if/else before linear
//              statements, so validates after vote-count increment in the output.
//              Reorder the require! guards to the top of fn vote() when deploying.

#![no_std]

use multiversx_sc::imports::*;

#[derive(TypeAbi, TopEncode, TopDecode, NestedEncode, NestedDecode, ManagedVecItem)]
pub struct Proposal<M: ManagedTypeApi> {
    pub id: BigUint<M>,
    pub description: ManagedBuffer<M>,
    pub voteCount: BigUint<M>,
    pub against: BigUint<M>,
    pub executed: bool,
    pub deadline: BigUint<M>
}

#[multiversx_sc::contract]
pub trait DaoGovernance {
    #[storage_mapper("owner")]
    fn owner(&self) -> SingleValueMapper<ManagedAddress<Self::Api>>;

    #[storage_mapper("proposalCount")]
    fn proposal_count(&self) -> SingleValueMapper<BigUint<Self::Api>>;

    #[storage_mapper("quorum")]
    fn quorum(&self) -> SingleValueMapper<BigUint<Self::Api>>;

    #[storage_mapper("votingDuration")]
    fn voting_duration(&self) -> SingleValueMapper<BigUint<Self::Api>>;

    #[storage_mapper("hasVoted")]
    fn has_voted(&self, key1: &BigUint<Self::Api>, key2: &ManagedAddress<Self::Api>) -> SingleValueMapper<bool>;

    #[storage_mapper("proposals")]
    fn proposals(&self, key: &BigUint<Self::Api>) -> SingleValueMapper<Proposal>;

    #[event("ProposalCreated")]
    fn proposal_created_event(&self, #[indexed] id: &BigUint<Self::Api>, #[indexed] proposer: &ManagedAddress<Self::Api>, deadline: &BigUint<Self::Api>);

    #[event("VoteCast")]
    fn vote_cast_event(&self, #[indexed] proposalId: &BigUint<Self::Api>, #[indexed] voter: &ManagedAddress<Self::Api>, support: &bool);

    #[event("ProposalExecuted")]
    fn proposal_executed_event(&self, #[indexed] proposalId: &BigUint<Self::Api>);

    #[init]
    fn init(&self) {
        self.owner().set(&(self.blockchain().get_caller()));
        self.proposal_count().set(&(BigUint::from(0u32)));
        self.quorum().set(&(BigUint::from(3u32)));
        self.voting_duration().set(&(BigUint::from(86400u32)));
    }

    #[endpoint]
    fn create_proposal(&self, description: ManagedBuffer<Self::Api>) -> BigUint<Self::Api> {
        self.proposal_count().set(&(self.proposal_count().get() + BigUint::from(1u32)));
        let mut id: BigUint<Self::Api> = self.proposal_count().get();
        let mut deadline: BigUint<Self::Api> = self.blockchain().get_block_timestamp() + self.voting_duration().get();
        let mut s = self.proposals(&id).get();
        s.id = id;
        self.proposals(&id).set(&s);
        let mut s = self.proposals(&id).get();
        s.vote_count = BigUint::from(0u32);
        self.proposals(&id).set(&s);
        let mut s = self.proposals(&id).get();
        s.against = BigUint::from(0u32);
        self.proposals(&id).set(&s);
        let mut s = self.proposals(&id).get();
        s.executed = false;
        self.proposals(&id).set(&s);
        let mut s = self.proposals(&id).get();
        s.deadline = deadline;
        self.proposals(&id).set(&s);
        self.proposal_created_event(&id, &self.blockchain().get_caller(), &deadline);
        return id;
    }

    #[endpoint]
    fn vote(&self, proposalId: BigUint<Self::Api>, support: bool) {
        if support {
        let mut s = self.proposals(&proposalId).get();
        s.vote_count = self.proposals(&proposalId).voteCount + BigUint::from(1u32);
        self.proposals(&proposalId).set(&s);
        } else {
        let mut s = self.proposals(&proposalId).get();
        s.against = self.proposals(&proposalId).against + BigUint::from(1u32);
        self.proposals(&proposalId).set(&s);
        }
        require!(proposalId > BigUint::from(0u32), "Invalid proposal");
        require!(self.blockchain().get_block_timestamp() <= self.proposals(&proposalId).deadline, "Voting closed");
        require!(!self.has_voted(&proposalId, &self.blockchain().get_caller()), "Already voted");
        self.vote_cast_event(&proposalId.clone(), &self.blockchain().get_caller(), &support);
    }

    #[endpoint]
    fn execute(&self, proposalId: BigUint<Self::Api>) {
        require!(self.blockchain().get_block_timestamp() > self.proposals(&proposalId).deadline, "Voting still open");
        require!(!self.proposals(&proposalId).executed, "Already executed");
        require!(self.proposals(&proposalId).voteCount >= self.quorum().get(), "Quorum not reached");
        let mut s = self.proposals(&proposalId).get();
        s.executed = true;
        self.proposals(&proposalId).set(&s);
        self.proposal_executed_event(&proposalId.clone());
    }

    #[view(getVoteCount)]
    fn get_vote_count(&self, id: BigUint<Self::Api>) -> BigUint<Self::Api> {
        return self.proposals(&id).voteCount;
    }

    #[view(getDeadline)]
    fn get_deadline(&self, id: BigUint<Self::Api>) -> BigUint<Self::Api> {
        return self.proposals(&id).deadline;
    }

    #[view(didVote)]
    fn did_vote(&self, proposalId: BigUint<Self::Api>, voter: ManagedAddress<Self::Api>) -> bool {
        return self.has_voted(&proposalId, &voter);
    }

    #[endpoint]
    fn set_quorum(&self, newQuorum: BigUint<Self::Api>) {
        require!(self.blockchain().get_caller() == owner, "Not owner");
        require!(newQuorum > BigUint::from(0u32), "Quorum must be positive");
        self.quorum().set(&newQuorum);
    }

}
