// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    nft_staking
    (
        init => init
        stake => stake
        unstake => unstake
        claimRewards => claim_rewards
        getStakeInfo => get_stake_info
        isStaked => is_staked
        setRewardRate => set_reward_rate
        setLockPeriod => set_lock_period
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
