// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    subscription
    (
        init => init
        registerService => register_service
        addPlan => add_plan
        deactivatePlan => deactivate_plan
        subscribe => subscribe
        renew => renew
        cancel => cancel
        isActive => is_active
        planCount => plan_count
        withdraw => withdraw
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
