// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            4
// Async Callback (empty):               1
// Total number of exported functions:   6

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    voting
    (
        init => init
        add_proposal => add_proposal
        vote => vote
        getProposalVoteCount => get_proposal_vote_count
        getProposalCount => get_proposal_count
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
