// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    dao_governance
    (
        init => init
        createProposal => create_proposal
        vote => vote
        execute => execute
        getVoteCount => get_vote_count
        getDeadline => get_deadline
        didVote => did_vote
        setQuorum => set_quorum
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
